name: Increment Revision

on:
  push:
    branches:
      - main

jobs:
  increment_revision_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: https://github.com/aiswaryajoykaniamkunnel/VERSION

      - name: Get current revision
        id: get_revision
        run: |
          echo "CURRENT_REVISION=${{vars.PAT}}" 

      - name: Increment revision
        id: increment_revision
        run: |
          echo "NEW_REVISION=$(( ${{vars.PAT}} + 1 ))" 
          echo "$NEW_REVISION "> secret.txt
          echo ${{ secrets.PAT }}

      - name: Update secret
        uses: https://github.com/aiswaryajoykaniamkunnel/VERSION
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
          commit_message: 'Update secret value'
          files: |
            secret.txt

      - name: Debug GitHub token
        run: |
          echo "GitHub Token: ${{ secrets.PAT }}"

      - name: Push changes
        uses: https://github.com/aiswaryajoykaniamkunnel/VERSION
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
