name: Change and Display Repository Variable

on:
  push:
    branches:
      - main

jobs:
  change_and_display_variable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull changes
        run: git pull origin main

      - name: Change variable value
        id: change_variable
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: repo } = await github.repos.get({ owner: context.repo.owner, repo: context.repo.repo });
            const variableName = 'VERSION'; // Change this to your variable's name
            const { data: currentSecret } = await github.actions.getRepoSecret({ owner: context.repo.owner, repo: context.repo.repo, secret_name: variableName });
            const currentValue = currentSecret.value;
            const newValue = parseInt(currentValue) + 1; // Increment current value by 1
            const { data: updatedSecret } = await github.actions.createOrUpdateRepoSecret({ owner: context.repo.owner, repo: context.repo.repo, secret_name: variableName, encrypted_value: Buffer.from(newValue.toString()).toString('base64') });
            
            // Return the new value
            return newValue;

      - name: Push changes
        run: git push origin main

      - name: Display new value
        run: |
          echo "New value of the variable: ${{ steps.change_variable.outputs.result }}"
