name: Change and Display Repository Variable

on:
  push:
    branches:
      - main

jobs:
  change_and_display_variable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull changes
        run: git pull origin main

      - name: Change variable value
        id: change_variable
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: repo } = await github.repos.get({ owner: context.repo.owner, repo: context.repo.repo });
            console.log("Repository data:", repo);
            const variableName = 'PAT_VAR'; // Change this to your variable's name
            const { data: currentSecret } = await github.actions.getRepoSecret({ owner: context.repo.owner, repo: context.repo.repo, secret_name: variableName });
            console.log("Current secret:", currentSecret);
            const currentValue = currentSecret.value;
            console.log("Current value:", currentValue);
            const newValue = parseInt(currentValue) + 1; // Increment current value by 1
            console.log("New value:", newValue);
            const { data: updatedSecret } = await github.actions.createOrUpdateRepoSecret({ owner: context.repo.owner, repo: context.repo.repo, secret_name: variableName, key_id: currentSecret.key_id, key_id: currentSecret.key_id, encrypted_value: Buffer.from(newValue.toString()).toString('base64') });
            console.log("Updated secret:", updatedSecret);
            
            // Return the new value
            return newValue;

      - name: Commit changes
        run: |
          git config --global user.email "aiswaryajoypp@gmail.com"
          git config --global user.name "aiswaryajoykaniamkunnel"
          git add .
          git commit -m "Update repository variable"

      - name: Push changes
        run: git push origin main

      - name: Display new value
        run: |
          echo "New value of the variable: ${{ steps.change_variable.outputs.result  }}"
