name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}

      - name: Output Run ID
        run: git rev-list --count --first-parent HEAD 

      - name: Output Run Number
        run: echo ${{ github.run_number }}