name: Increment Revision

on:
  push:
    branches:
      - main

jobs:
  increment_revision_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current revision
        id: get_revision
        run: |
          echo "CURRENT_REVISION=${{vars.PAT}}" 

      - name: Increment revision
        id: increment_revision
        run: |
          echo ${{ secrets.PAT }}

      - name: Update secret
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const fs = require('fs');
            const NEW_REVISION= ( ${{vars.PAT}} + 1 )
            const secretValue = NEW_REVISION;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const response = await octokit.request('PUT /repos/{owner}/{repo}/actions/secrets/{secret_name}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            secret_name: 'PAT', // Replace with your secret name
            data: {
              encrypted_value: Buffer.from(secretValue).toString('base64')
              }
            });

      - name: Debug GitHub token
        run: |
          echo "GitHub Token: ${{ secrets.PAT }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
