name: Greeting on variable day

on:
  push:
    branches: 
      - main

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Set initial version
        run: echo "version=1" >> $GITHUB_ENV
      
      - name: Increment version
        run: echo "version=$(( ${{ env.version }} + 1 ))" >> $GITHUB_ENV
      
      - name: Say Hello with version
        run: |
          echo "${{ env.Greeting }} version number ${{ env.version }}"
