name: Increment Revision

on:
  push:
    branches:
      - main

jobs:
  increment_revision_job:
    runs-on: ubuntu-latest

    steps:
      - name: Install @actions/github
        run: npm install @actions/github

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current revision
        id: get_revision
        run: |
          echo "CURRENT_REVISION=${{vars.PAT}}" 

      - name: Increment revision
        id: increment_revision
        run: |
          echo ${{ secrets.PAT }}

      - name: Install @octokit/core
        run: npm install @octokit/core

      - name: Update secret
        run: node update-secret.js
        
      - name: Debug GitHub token
        run: |
          echo "GitHub Token: ${{ secrets.PAT }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
