name: Change and Display Repository Variable

on:
  push:
    branches:
      - main

jobs:
  change_and_display_variable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Define the PAT secret
      - name: Set up PAT secret
        run: echo "PAT=${{ secrets.PAT }}" >> $GITHUB_ENV

      - name: Pull changes
        run: git pull origin main

      - name: Get current variable value
        id: get_current_value
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: currentSecret } = await github.actions.getRepoSecret({ owner: context.repo.owner, repo: context.repo.repo, secret_name: 'PAT' }); // Change to your variable's name
            return currentSecret.value;

      - name: Calculate new value
        id: calculate_new_value
        run: |
          current_value="${{ steps.get_current_value.outputs.result }}"
          new_value=$(( current_value + 1 ))
          echo "Current value: $current_value"
          echo "New value: $new_value"     
      
      - name: Commit changes
        run: |
          git config --global user.email "aiswaryajoypp@gmail.com"
          git config --global user.name "aiswaryajoykaniamkunnel"
          git add .
          git commit -m "Update repository variable"

      - name: Push changes
        run: git push origin main

      - name: Display new value
        run: |
          echo "New value of the variable: ${{ steps.change_variable.outputs.result  }}"
