name: Greeting on variable day

on:
  push:
    branches: 
      - main

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:      
      - name: Increment version
        run: echo "$((${{vars.version}}))=$(( ${{ vars.version }} + 1 ))" 
      
      - name: Say Hello with version
        run: |
          echo "${{ env.Greeting }} version number ${{ vars.version }}"
