name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}

      - name: Output Run ID
        run: |
          git rev-list HEAD | wc -l
      
      - name: Output Run git rev-list --count HEAD 
        run: |
          git rev-list --count HEAD 
          

      - name: Output Run git rev-list --count HEAD 
        run: echo $GITHUB_RUN_ATTEMPT

      - name: Output Run Number
        run: echo ${{ github.run_number }}