name: Change and Display Repository Variable

on:
  push:
    branches:
      - main

jobs:
  change_and_display_variable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Debugging step: Print out all repository secrets
      - name: List repository secrets
        run: |
          echo "Repository Secrets:"
          curl -X GET -H "Authorization: Bearer ${{ secrets.PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/secrets" | jq .

      # Get current variable value
      - name: Get current variable value
        id: get_current_value
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: currentSecret } = await github.actions.getRepoSecret({ owner: context.repo.owner, repo: context.repo.repo, secret_name: 'PAT' });
            console.log('Current Secret:', currentSecret);
            return currentSecret.value;

      - name: Calculate new value
        id: calculate_new_value
        run: |
          current_value="${{ steps.get_current_value.outputs.result }}"
          echo "$current_value"
          new_value=$(( current_value + 1 ))
          echo "Current value: $current_value"
          echo "New value: $new_value"     

      - name: Display new value
        run: |
          echo "New value of the variable: ${{ steps.calculate_new_value.outputs.result }}"
