name: Greeting on variable day

on:
  push:
    branches: 
      - main

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      version: 1  # Initial value of version
    steps:
      - name: Update version
        run: echo "version=$(( ${{ env.version }} + 1 ))" >> $GITHUB_ENV
      
      - name: Say Hello with updated version
        run: |
          echo "${{ env.Greeting }} version number ${{ env.version }} "
